name: wireguard-ui build release

on:
  push:
    branches: [ master, main ]

jobs:
  releases-docker:
    name: Release docker
    runs-on: ubuntu-latest
    steps:
    # get the source code
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      if: success() && github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: build the image
      run: |
        docker buildx build --push \
          --tag mjasion/wireguard-ui:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
